// export const FETCH_POKEMON_BEGIN = 'FETCH_POKEMON_BEGIN';
// export const FETCH_POKEMON_SUCCESS = 'FETCH_POKEMON_SUCCESS';
// export const FETCH_POKEMON_FAILURE = 'FETCH_POKEMON_FAILURE';

export const FETCH_POKEMON = 'FETCH_POKEMON';
export const ADD_POKEMON = 'ADD_POKEMON';
export const DELETE_POKEMON = 'DELETE_POKEMON';
export const EDIT_POKEMON = 'EDIT_POKEMON';
export const FILTER_BY_TYPE = 'FILTER_BY_TYPE';